In [1]:
import pandas as pd

In [2]:
BMI_male_df = pd.read_csv('BMI_Male.csv')

In [3]:
Obesity_df = pd.read_csv('Obesity_data.csv')

In [4]:
Population_df = pd.read_csv('Population_data.csv')

In [5]:
Continent_df = pd.read_csv('Continents_data.csv')

In [6]:
filtered_BMI_male_df = BMI_male_df.loc[(BMI_male_df['Year'] == 2016), ['Entity','Mean BMI (male)']]

In [7]:
filtered_BMI_male_df.rename(columns={'Entity':'Country'},inplace=True)

In [8]:
filtered_BMI_male_df

             Country  Mean BMI (male)
41       Afghanistan        22.682456
83           Albania        27.174471
125          Algeria        24.865386
167   American Samoa        33.066721
209          Andorra        27.478395
...              ...              ...
8651         Vietnam        21.970528
8693           World        24.457105
8735           Yemen        23.726697
8777          Zambia        21.448027
8819        Zimbabwe        22.301353

[210 rows x 2 columns]

In [9]:
Obesity_df

                                Country Obesity (%)
0                           Afghanistan         5.5
1                               Albania        21.7
2                               Algeria        27.4
3                               Andorra        25.6
4                                Angola         8.2
..                                  ...         ...
190  Venezuela (Bolivarian Republic of)        25.6
191                            Viet Nam         2.1
192                               Yemen        17.1
193                              Zambia         8.1
194                            Zimbabwe        15.5

[195 rows x 2 columns]

In [10]:
Population_df = Population_df.dropna()

In [11]:
Population_df['2016'] = Population_df['2016'].astype(int)

In [12]:
Population_df.rename(columns={'Country Name':'Country','2016':'Population_2016'},inplace=True)

In [13]:
Population_df

                         Country  Population_2016
0                          Aruba           108727
1    Africa Eastern and Southern        623369401
2                    Afghanistan         34700612
3     Africa Western and Central        429454743
4                         Angola         29183070
..                           ...              ...
261                       Kosovo          1777568
262                  Yemen, Rep.         32109010
263                 South Africa         57259551
264                       Zambia         16914423
265                     Zimbabwe         14600294

[265 rows x 2 columns]

In [14]:
merge_df = pd.merge(filtered_BMI_male_df,Obesity_df, on='Country',how='inner')

In [15]:
merge_df = pd.merge(merge_df,Population_df, on = 'Country', how = 'inner')

In [19]:
Continent_df

         Continent    Country
0           Africa    Algeria
1           Africa     Angola
2           Africa      Benin
3           Africa   Botswana
4           Africa    Burkina
..             ...        ...
191  South America   Paraguay
192  South America       Peru
193  South America   Suriname
194  South America    Uruguay
195  South America  Venezuela

[196 rows x 2 columns]

In [20]:
merge_df = pd.merge(merge_df,Continent_df, on = 'Country', how = 'inner')

In [22]:
merge_df

         Country  Mean BMI (male) Obesity (%)  Population_2016      Continent
0    Afghanistan        22.682456         5.5         34700612           Asia
1        Albania        27.174471        21.7          2876101         Europe
2        Algeria        24.865386        27.4         40850721         Africa
3        Andorra        27.478395        25.6            72181         Europe
4         Angola        22.436538         8.2         29183070         Africa
..           ...              ...         ...              ...            ...
149      Uruguay        27.529697        27.9          3379283  South America
150   Uzbekistan        26.488104        16.6         31284568           Asia
151      Vanuatu        25.711030        25.2           272087        Oceania
152       Zambia        21.448027         8.1         16914423         Africa
153     Zimbabwe        22.301353        15.5         14600294         Africa

[154 rows x 5 columns]

In [23]:
merge_df.to_csv('Male_BMI_Obesity.csv')