In [1]:
import pandas as pd

In [2]:
Obesity_df = pd.read_csv('Obesity_data.csv')

In [3]:
Obesity_df

                                Country Obesity (%)
0                           Afghanistan         5.5
1                               Albania        21.7
2                               Algeria        27.4
3                               Andorra        25.6
4                                Angola         8.2
..                                  ...         ...
190  Venezuela (Bolivarian Republic of)        25.6
191                            Viet Nam         2.1
192                               Yemen        17.1
193                              Zambia         8.1
194                            Zimbabwe        15.5

[195 rows x 2 columns]

In [4]:
Continent_df = pd.read_csv('Continents_data.csv')

In [5]:
Continent_df

         Continent    Country
0           Africa    Algeria
1           Africa     Angola
2           Africa      Benin
3           Africa   Botswana
4           Africa    Burkina
..             ...        ...
191  South America   Paraguay
192  South America       Peru
193  South America   Suriname
194  South America    Uruguay
195  South America  Venezuela

[196 rows x 2 columns]

In [6]:
Obesity_continent_df = pd.merge(Obesity_df,Continent_df,on = 'Country',how = 'inner')

In [8]:
Obesity_continent_df.to_csv('Data_for_Box_and_Whisker.csv')

In [9]:
Full_Obesity = pd.read_csv('Full_obesity_data.csv')

In [10]:
Full_Obesity

       Unnamed: 0      Country  Year       Obesity (%)         Sex
0               0  Afghanistan  1975     0.5 [0.2-1.1]  Both sexes
1               1  Afghanistan  1975     0.2 [0.0-0.6]        Male
2               2  Afghanistan  1975     0.8 [0.2-2.0]      Female
3               3  Afghanistan  1976     0.5 [0.2-1.1]  Both sexes
4               4  Afghanistan  1976     0.2 [0.0-0.7]        Male
...           ...          ...   ...               ...         ...
24565       24565     Zimbabwe  2015     4.5 [2.4-7.6]        Male
24566       24566     Zimbabwe  2015  24.8 [18.9-31.3]      Female
24567       24567     Zimbabwe  2016  15.5 [12.0-19.2]  Both sexes
24568       24568     Zimbabwe  2016     4.7 [2.5-8.0]        Male
24569       24569     Zimbabwe  2016  25.3 [19.1-32.0]      Female

[24570 rows x 5 columns]

In [11]:
australia_obesity = Full_Obesity.loc[(Full_Obesity['Country']=='Australia'),['Country','Year','Obesity (%)','Sex']]

In [13]:
australia_obesity = australia_obesity.dropna()

In [14]:
australia_obesity

        Country  Year       Obesity (%)         Sex
1008  Australia  1975   10.5 [7.9-13.4]  Both sexes
1009  Australia  1975    9.7 [6.2-13.9]        Male
1010  Australia  1975   11.2 [7.6-15.2]      Female
1011  Australia  1976   10.8 [8.2-13.5]  Both sexes
1012  Australia  1976   10.0 [6.6-14.0]        Male
...         ...   ...               ...         ...
1129  Australia  2015  28.9 [23.9-34.3]        Male
1130  Australia  2015  27.9 [23.0-33.1]      Female
1131  Australia  2016  29.0 [25.3-32.9]  Both sexes
1132  Australia  2016  29.6 [24.2-35.3]        Male
1133  Australia  2016  28.4 [23.1-33.9]      Female

[126 rows x 4 columns]

In [15]:
def retrieve_val(x):
    val_lst = x.split('[')
    return val_lst[0]

In [16]:
australia_obesity['Obesity (%)'] = australia_obesity['Obesity (%)'].apply(retrieve_val)

In [18]:
australia_obesity.to_csv('Australia_obesity_data.csv')

In [19]:
BMI_female_df = pd.read_csv('BMI_Female.csv')

In [20]:
BMI_female_df

           Entity Code  Year  Mean BMI (female)
0     Afghanistan  AFG  1975          18.844326
1     Afghanistan  AFG  1976          18.986417
2     Afghanistan  AFG  1977          19.128086
3     Afghanistan  AFG  1978          19.269247
4     Afghanistan  AFG  1979          19.409477
...           ...  ...   ...                ...
8815     Zimbabwe  ZWE  2012          25.284840
8816     Zimbabwe  ZWE  2013          25.319948
8817     Zimbabwe  ZWE  2014          25.356222
8818     Zimbabwe  ZWE  2015          25.393409
8819     Zimbabwe  ZWE  2016          25.431487

[8820 rows x 4 columns]

In [21]:
filtered_BMI_female_df = BMI_female_df.loc[(BMI_female_df['Year'] == 2016),['Entity','Mean BMI (female)']]

In [23]:
filtered_BMI_female_df.rename(columns={'Entity':'Country'},inplace=True)

In [24]:
filtered_BMI_female_df

             Country  Mean BMI (female)
41       Afghanistan          24.234135
83           Albania          26.507512
125          Algeria          26.561166
167   American Samoa          35.148865
209          Andorra          26.271661
...              ...                ...
8651         Vietnam          21.940594
8693           World          24.751606
8735           Yemen          24.197709
8777          Zambia          23.833982
8819        Zimbabwe          25.431487

[210 rows x 2 columns]

In [25]:
Population_df = pd.read_csv('Population_data.csv')

In [26]:
Population_df

                    Country Name         2016
0                          Aruba     108727.0
1    Africa Eastern and Southern  623369401.0
2                    Afghanistan   34700612.0
3     Africa Western and Central  429454743.0
4                         Angola   29183070.0
..                           ...          ...
261                       Kosovo    1777568.0
262                  Yemen, Rep.   32109010.0
263                 South Africa   57259551.0
264                       Zambia   16914423.0
265                     Zimbabwe   14600294.0

[266 rows x 2 columns]

In [28]:
Population_df = Population_df.dropna()

In [29]:
Population_df['2016'] = Population_df['2016'].astype(int)

C:\Users\yiton\AppData\Local\Temp\ipykernel_29476\2170702154.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Population_df['2016'] = Population_df['2016'].astype(int)

In [30]:
Population_df

                    Country Name       2016
0                          Aruba     108727
1    Africa Eastern and Southern  623369401
2                    Afghanistan   34700612
3     Africa Western and Central  429454743
4                         Angola   29183070
..                           ...        ...
261                       Kosovo    1777568
262                  Yemen, Rep.   32109010
263                 South Africa   57259551
264                       Zambia   16914423
265                     Zimbabwe   14600294

[265 rows x 2 columns]

In [31]:
Population_df.rename(columns={'Country Name':'Country','2016':'Population_2016'},inplace=True)

C:\Users\yiton\AppData\Local\Temp\ipykernel_29476\3476402091.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Population_df.rename(columns={'Country Name':'Country','2016':'Population_2016'},inplace=True)

In [32]:
Population_df

                         Country  Population_2016
0                          Aruba           108727
1    Africa Eastern and Southern        623369401
2                    Afghanistan         34700612
3     Africa Western and Central        429454743
4                         Angola         29183070
..                           ...              ...
261                       Kosovo          1777568
262                  Yemen, Rep.         32109010
263                 South Africa         57259551
264                       Zambia         16914423
265                     Zimbabwe         14600294

[265 rows x 2 columns]

In [33]:
merge_df = pd.merge(filtered_BMI_female_df,Obesity_df, on = 'Country', how = 'inner')

In [34]:
merge_df = pd.merge(merge_df,Population_df, on = 'Country', how = 'inner')

In [35]:
Continent_df = pd.read_csv('Continents_data.csv')

In [36]:
merge_df = pd.merge(merge_df,Continent_df, on = 'Country', how = 'inner')

In [38]:
merge_df.to_csv('Female_BMI_Obesity.csv')

In [3]:
#Fix issue for data of box and whisker
box_and_whisker_df = pd.read_csv('Data_for_Box_and_Whisker.csv')

In [4]:
box_and_whisker_df_final = box_and_whisker_df.dropna()

In [8]:
box_and_whisker_df_final

     Unnamed: 0      Country Obesity (%) Continent
0             0  Afghanistan         5.5      Asia
1             1      Albania        21.7    Europe
2             2      Algeria        27.4    Africa
3             3      Andorra        25.6    Europe
4             4       Angola         8.2    Africa
..          ...          ...         ...       ...
164         164   Uzbekistan        16.6      Asia
165         165      Vanuatu        25.2   Oceania
166         166        Yemen        17.1      Asia
167         167       Zambia         8.1    Africa
168         168     Zimbabwe        15.5    Africa

[169 rows x 4 columns]

In [9]:
box_and_whisker_df_final.to_csv('Final_box_and_whisker_data.csv')

In [25]:
Life_Expectancy_final_df = pd.read_csv('Life_Expectancy_fixed_data.csv')

In [26]:
Life_Expectancy_final_df

,Country,Year,Continent,Least Developed,Life Expectancy,Population,CO2 emissions,Health expenditure,Electric power consumption,Forest area,GDP per capita,Individuals using the Internet,Military expenditure,People practicing open defecation,People using at least basic drinking water services,Obesity among adults,Beer consumption per capita
0,Albania,2000,Europe,False,73.955,3089027,1.026213,7.233370,1414.703784,28.076642,3860.804627,0.114097,1.246360,0.888853,86.754471,12.8,1.33431
1,Albania,2001,Europe,False,74.288,3060173,1.055496,7.139524,1449.647413,28.123248,4299.546493,0.325798,1.309291,0.836397,86.904070,13.3,1.48995
2,Albania,2002,Europe,False,74.579,3051010,1.232379,6.909341,1351.230796,28.169854,4661.402695,0.390081,1.320034,0.781899,87.451635,13.9,1.28697
3,Albania,2003,Europe,False,74.828,3039616,1.338985,7.063490,1578.165919,28.216460,5000.049363,0.971900,1.336843,0.728191,87.987194,14.4,1.44830
4,Albania,2004,Europe,False,75.039,3026939,1.404059,6.773372,1469.264539,28.263066,5427.732662,2.420388,1.381158,0.675281,88.510583,15.0,1.37617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,Zimbabwe,2011,Africa,False,52.896,12894323,0.884886,8.081738,606.643960,46.165723,2101.824051,8.400000,1.407162,26.876148,67.016076,10.8,2.05000
1900,Zimbabwe,2012,Africa,False,55.032,13115149,0.915735,6.918354,636.248991,46.046633,2375.927006,12.000000,1.859609,26.533231,66.491185,11.1,2.07000
1901,Zimbabwe,2013,Africa,False,56.897,13350378,0.919824,7.110148,608.761669,45.927543,2560.773267,15.500000,1.868420,26.188786,65.966474,11.3,2.12000
1902,Zimbabwe,2014,Africa,False,58.410,13586710,0.889104,8.133525,628.746242,45.808453,2612.455954,16.364740,1.888080,25.832157,65.454108,11.6,2.23000
1903,Zimbabwe,2015,Africa,False,59.534,13814642,0.899770,7.452066,609.124652,45.689363,2679.507615,22.742818,1.886876,25.463272,64.954929,11.9,1.93000

In [27]:
filtered_Life_Expectancy_final_df = Life_Expectancy_final_df.loc[Life_Expectancy_final_df['Year']==2015,['Country','Continent','Life Expectancy','Population','Obesity among adults']]

In [28]:
filtered_Life_Expectancy_final_df.rename(columns={'Obesity among adults':'Obesity (%)'},inplace=True)

In [29]:
filtered_Life_Expectancy_final_df

            Country      Continent  Life Expectancy  Population  Obesity (%)
15          Albania         Europe        78.025000     2880703         21.7
31          Algeria         Africa        76.090000    39728020         25.7
47           Angola         Africa        59.398000    27884380          6.5
63        Argentina  South America        76.068000    43131966         28.0
79          Armenia           Asia        74.467000     2925559         20.2
...             ...            ...              ...         ...          ...
1839  United States  North America        78.690244   320738994         36.7
1855        Uruguay  South America        77.369000     3412013         28.4
1871      Venezuela  South America        72.762000    30042973         24.7
1887          Yemen           Asia        66.066000    25823488         13.5
1903       Zimbabwe         Africa        59.534000    13814642         11.9

[119 rows x 5 columns]

In [30]:
filtered_Life_Expectancy_final_df.to_csv('Life_Expectancy_final_bubble_chart_data.csv')